### ISSUE TITLE
Подключение апи без composer.

### ISSUE THREAD

**Issue by GedxBlood** [ddlzz/amocrm-api-client#2]
Добрый день. Неопытен, отсюда возник глупый вопрос.

Как мне правильно прикрепить апи клиент к проекту на codeigniter без composer? Какой самый простой способ подключить пакет, не дописывая обертку под library и не пользуя composer?

**Comment by ddlzz** [comment]
@GedxBlood https://github.com/ddlzz/amocrm-api-client/releases тут можно скачать исходники в архиве. написать свой автолоадер все же придется, но проблем возникнуть не должно
