### ISSUE TITLE
#При добавлении лида и указании воронки происходит исключение

### ISSUE THREAD

**Issue by Aleksej-Shherbak** [ddlzz/amocrm-api-client#6]
Я пытаюсь создать лид.  При этом, мне необходимо иметь возможность указать, к какой воронке данный лид будет принадлежать. Вижу, что возможность этого предусмотрена 
   
      'contacts_id' => [
            'type' => 'array|string', // [id => int, id => int]
            'required_add' => false,
            'required_update' => false,
        ],
        'pipeline' => [
            'type' => 'array', // [id => int, _links => array]
            'required_add' => false,
            'required_update' => false,
        ],
        'pipeline_id' => [
            'type' => 'int',
            'required_add' => false,
            'required_update' => false,
        ],

Это отрывок из класса Lead. У себя, в клиентском коде пишу следующее:

    $lead['pipeline_id'] = intval(env('AMO_PIPELINE_ID'));

Казалось бы логично, правда? Но потом происходит сюрприз в этом методе (а он вызывается всегда):

     private function renameAliases(array $data)
      {
           foreach ($data as $key => $value) {
               if (in_array($key, $this->aliases, true)) {
                    $newKey = array_search($key, $this->aliases, true);
                    $data[$newKey] = $data[$key];
                    unset($data[$key]);
               }
        }

        return $data;
    }

Как видите, он заменяет некоторые наименования передаваемых полей на алиасы (видимо задумка для совместимости со старым апи). Сами алиасы в том же классе Lead:

    /** @var array */
    protected $aliasesAppend = [
        'is_deleted' => 'deleted',
        'main_contact' => 'main_contact_id',
        'company' => 'linked_company_id',
        'closed_at' => 'date_close',
        'closest_task_at' => 'closest_task',
        'sale' => 'price',
        'pipeline' => 'pipeline_id',
    ]; 

То есть, pipeline_id будет заменен на pipeline. А валидация требует, чтоб pipeline был массивом. Происходит исключение. Пробовал обойти это разными способами. Пытался использовать pipeline и передавать массив вида 

    ['id' => тут id]

Но это не работает. Правильный json, который должен быть отправлен для генерации лида и установки его в воронку должен быть таким: 
  
      {  
       "add":[  
          {  
             "created_at":1536747960,
             "name":"New pickup user lel",
             "custom_fields":[  
                {  
                   "id":"544395",
                   "values":[  
                      {  
                         "value":"lel"
                      }
                   ]
                }
             ],
             "pipeline_id":1336759
          }
       ]
    }

Помогите пожалуйста корректно указать воронку для нового лида.

**Comment by Aleksej-Shherbak** [comment]
@abramovku по-моему, лезть в исходники пакета - плохая идея. Я предложил пул-реквест но никакой реакции не получил (

**Comment by alyamovsky** [comment]
прошу прощения за задержку в полтора года, вмержил МР
